// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	APIKeyAuthScopes = "APIKeyAuth.Scopes"
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for GetCoveragePathParamsFormat.
const (
	Raw GetCoveragePathParamsFormat = "raw"
	Svg GetCoveragePathParamsFormat = "svg"
)

// APIKey defines model for APIKey.
type APIKey struct {
	Id  int    `json:"id"`
	Key string `json:"key"`
}

// APIKeyInit defines model for APIKeyInit.
type APIKeyInit struct {
	Scopes []string `json:"scopes"`
}

// APIKeyRef defines model for APIKeyRef.
type APIKeyRef struct {
	Id int `json:"id"`
}

// APIKeyUpdate defines model for APIKeyUpdate.
type APIKeyUpdate struct {
	Id     int      `json:"id"`
	Scopes []string `json:"scopes"`
}

// ExpectedError defines model for ExpectedError.
type ExpectedError struct {
	// Code the error code of the responses
	Code int `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// HealthCheck Information on the health of the service
type HealthCheck = string

// SigninData Data used to sign in
type SigninData struct {
	// Password Password used to sign in
	Password string `json:"password"`

	// Username Username used to sign in
	Username string `json:"username"`
}

// Success Operation was a success
type Success struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// APIKeyResponse defines model for APIKeyResponse.
type APIKeyResponse = APIKey

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ExpectedError

// HealthCheckResponse Information on the health of the service
type HealthCheckResponse = HealthCheck

// SuccessResponse Operation was a success
type SuccessResponse = Success

// SuccessfulSigninResponse Operation was a success
type SuccessfulSigninResponse = Success

// SuccessfulSignoutResponse Operation was a success
type SuccessfulSignoutResponse = Success

// APIKeyInitBody defines model for APIKeyInitBody.
type APIKeyInitBody = APIKeyInit

// APIKeyRefBody defines model for APIKeyRefBody.
type APIKeyRefBody = APIKeyRef

// APIKeyUpdateBody defines model for APIKeyUpdateBody.
type APIKeyUpdateBody = APIKeyUpdate

// SigninDataBody Data used to sign in
type SigninDataBody = SigninData

// GetCoveragePathParams defines parameters for GetCoveragePath.
type GetCoveragePathParams struct {
	// Format Specifies the desired format
	Format *GetCoveragePathParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetCoveragePathParamsFormat defines parameters for GetCoveragePath.
type GetCoveragePathParamsFormat string

// PostCoveragePathJSONBody defines parameters for PostCoveragePath.
type PostCoveragePathJSONBody struct {
	Cover string `json:"cover"`
}

// PostCoveragePathJSONRequestBody defines body for PostCoveragePath for application/json ContentType.
type PostCoveragePathJSONRequestBody PostCoveragePathJSONBody

// DeleteKeysJSONRequestBody defines body for DeleteKeys for application/json ContentType.
type DeleteKeysJSONRequestBody = APIKeyRef

// GetKeysJSONRequestBody defines body for GetKeys for application/json ContentType.
type GetKeysJSONRequestBody = APIKeyRef

// PostKeysJSONRequestBody defines body for PostKeys for application/json ContentType.
type PostKeysJSONRequestBody = APIKeyInit

// PutKeysJSONRequestBody defines body for PutKeys for application/json ContentType.
type PutKeysJSONRequestBody = APIKeyUpdate

// PostUsersSigninJSONRequestBody defines body for PostUsersSignin for application/json ContentType.
type PostUsersSigninJSONRequestBody = SigninData

// PostUsersSignupJSONRequestBody defines body for PostUsersSignup for application/json ContentType.
type PostUsersSignupJSONRequestBody = SigninData

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /coverage/{path})
	DeleteCoveragePath(w http.ResponseWriter, r *http.Request, path string)

	// (GET /coverage/{path})
	GetCoveragePath(w http.ResponseWriter, r *http.Request, path string, params GetCoveragePathParams)

	// (POST /coverage/{path})
	PostCoveragePath(w http.ResponseWriter, r *http.Request, path string)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (DELETE /keys)
	DeleteKeys(w http.ResponseWriter, r *http.Request)

	// (GET /keys)
	GetKeys(w http.ResponseWriter, r *http.Request)

	// (POST /keys)
	PostKeys(w http.ResponseWriter, r *http.Request)

	// (PUT /keys)
	PutKeys(w http.ResponseWriter, r *http.Request)

	// (POST /users/signin)
	PostUsersSignin(w http.ResponseWriter, r *http.Request)

	// (POST /users/signout)
	PostUsersSignout(w http.ResponseWriter, r *http.Request)

	// (POST /users/signup)
	PostUsersSignup(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (DELETE /coverage/{path})
func (_ Unimplemented) DeleteCoveragePath(w http.ResponseWriter, r *http.Request, path string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /coverage/{path})
func (_ Unimplemented) GetCoveragePath(w http.ResponseWriter, r *http.Request, path string, params GetCoveragePathParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /coverage/{path})
func (_ Unimplemented) PostCoveragePath(w http.ResponseWriter, r *http.Request, path string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /keys)
func (_ Unimplemented) DeleteKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /keys)
func (_ Unimplemented) GetKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /keys)
func (_ Unimplemented) PostKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /keys)
func (_ Unimplemented) PutKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /users/signin)
func (_ Unimplemented) PostUsersSignin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /users/signout)
func (_ Unimplemented) PostUsersSignout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /users/signup)
func (_ Unimplemented) PostUsersSignup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteCoveragePath operation middleware
func (siw *ServerInterfaceWrapper) DeleteCoveragePath(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "path" -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCoveragePath(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetCoveragePath operation middleware
func (siw *ServerInterfaceWrapper) GetCoveragePath(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "path" -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCoveragePathParams

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", r.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCoveragePath(w, r, path, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostCoveragePath operation middleware
func (siw *ServerInterfaceWrapper) PostCoveragePath(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "path" -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx = context.WithValue(ctx, APIKeyAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCoveragePath(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteKeys operation middleware
func (siw *ServerInterfaceWrapper) DeleteKeys(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetKeys operation middleware
func (siw *ServerInterfaceWrapper) GetKeys(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostKeys operation middleware
func (siw *ServerInterfaceWrapper) PostKeys(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutKeys operation middleware
func (siw *ServerInterfaceWrapper) PutKeys(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostUsersSignin operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSignin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersSignin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostUsersSignout operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSignout(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersSignout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostUsersSignup operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSignup(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersSignup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/coverage/{path}", wrapper.DeleteCoveragePath)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/coverage/{path}", wrapper.GetCoveragePath)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/coverage/{path}", wrapper.PostCoveragePath)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/keys", wrapper.DeleteKeys)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/keys", wrapper.GetKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/keys", wrapper.PostKeys)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/keys", wrapper.PutKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/signin", wrapper.PostUsersSignin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/signout", wrapper.PostUsersSignout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/signup", wrapper.PostUsersSignup)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZX2/cuBH/KgTbp1axZCdoLxvkwXHSnJsWZ9h3RQrXD7Q0kphdkTpytPbC2O9eDKm/",
	"K+3at/bFZyBAZEqcGf5mOL+Z2Tse66LUChRaPrvjBn6twOIHnUhwC8dnp19gdaokra1oJdYKQSE9irJc",
	"yFig1Cr8ZrWiNRvnUAh6+rOBlM/4n8JORejf2rATy9fr9Tqo9ZxD+juoOYd0oOWXMhEIv4MiL7jWdSEz",
	"JdVHgeJJNXVinZ51wA3YUivb99d5vfTE5+NOXwI2NrIkKXzGjxU7Pjtlc1ixVBuGOTALZilj4OuAfxBJ",
	"BluskYXIILTL7K+3xWJoCq5K4DNu0UiVTWplsU6AxXoJRmTArkkPu/jPZ1L6yRhtnhyCT7clxAiJkz5l",
	"k3vBCrBWZO7wP4JYYH6SQzx/cmt6sqds8a9ZTO9Z4oIl4BdVHIO1T25LLXfKjvpVWi2YLsE46UzEc6Vv",
	"FpBkUJDyzrS0Wvj4fiYbrcwUk2MLA56DSMC4K3YB+OpE67l01m3IQm2gvgTW0mFPPzJhmWCx3xH07IVb",
	"UZQLF+j+Y5m8FzbJ029zYfMkzec2Sd+xM4H5+/Ad+xGx/EktVjwY348RhLrC58RQV7g/iB9hAThC8YEA",
	"Jm5zMobtHYPbUhqw73/OKxYdsn8KxQ7f/j1iUTRz/9jnf/88Ce66UdpLsfRUGgpqrKlSJgObDo9et7Kk",
	"QsjAUKTP/dbOdMylZdIy1CgWixUTbUKdsCVwDC0NJHx2SRq9wKv2S339DWJ3pXoUOzLVxrr0T60dlzyT",
	"mFfXB7EuQiOkUH87Ogz/woP+usu3yXXzP+mVCIWdyNmtRcIYsRqZXluw3XAi7b0gHmO0XUlN2Fv0jJ33",
	"/Lg5l+8Ab8hSo4MRa44vHN00cOzlWFWn7u51dUXQHfdN9GYqqhvWG4kekmIwiHtgpdFkOPtfFUWvYyUK",
	"cE/AEg2WKY0MbqXFey+CO1ZnxRQwfcIcWXmqUm0Kz05audPnnkFrLJqSpn+ATOtkbFm/8JtIbQIFqywk",
	"DHXDNjzYcFIprL3RJhlvP6vfTIjo7Gq3B7yQ6l+gMsz57IcJSysLhkAfK/qlfrNTkVkJWijEbaPkMIru",
	"c1WrM+gMnfJXQzYj035q64gbR6y2/jDYEuqtvUc946ZDtzua3qpk9+m6QHfqxwejJAJxZSSuLohS+lX7",
	"cUUY3nFJx/RcyQPuHcS/vjo+O3315dN/OxtEKV1RHnDPpIP9LV3W+1uGHO8no6RKtctGEh0AJ5SpPn4g",
	"KuIBX4KxHv3oIDqISKUuQYlS8hl/7ZbInZi704RNWR7e0dra+5BoeSvXt4U81aqukRBNcuBB543TpN1y",
	"Uu8gmnfKjSgAXXVxOb42mFMQ91NOo3F4pSdSeZOzA49r6fXVqNZ/dSGApoJgRydztdGvHUWH28qu9rtw",
	"s3BfB/zN16/37xs2Qv3YcyD1o+byikxDkRF+vAGXX60DngGO/XYOWBllHaRTrZhOd3jwM+Bvcd9FCbFM",
	"JXhtCViCmvmMPXCfXWaNm36twKw6P7Ufd55JIBXVAtttoKrCVSbuLyNuere3u+0vKrSi+0Nk2KBTYEVv",
	"9gmsycgptZ0InQvAqbhpb34PylHknGmLL/nmN9O13zYP2iS2JZghXb394eDoAUUS7ZugpNEQae+ktF/s",
	"DJJSnwq3JqV1wENfoJG+nQmqruNkr8JLjS5cRIiynMpNvlTk+1ynqZFP/3rUov0J5rCyD+DGQUM4RYVf",
	"SM4ouqYN7Y13w+HMdb3Peb87MxES7rxbmekfgHHuyAdeUfcgUapsK4KfAZ8Rvo1p7fdFbzo7nxgQu4OO",
	"cvDjMGt/TniBMVdWE6D5OcJO0KpHYtb70eLFoUbJjvo+G1rXGztOm64N6gFsZenS0h4WG0hAoRQLOxmK",
	"1Kpa33Pvg+7GzzSPwXY8vXacGD2mnnKnG0GofRDuwFBXGFCpjEavCEqiOwdn3QfuhpLkPx6I/gx6fyQe",
	"GG7TQFXldpzOIZMWgVpNh4z0gx+qQ6+Fhd0IVeUfM9jePkmwOdjNsqmpK7PgM54jlnYWhneJLoRU61CU",
	"Mlwe8oAvhZHieuEP4d8OO6y6kj7wBdfm8LGefxP2bi/DXCBb6cqwZgwhlUWhYqAPLSBDTXVr5/4Ri1Fr",
	"cdIV+nXR3q6MGzlXs/lZHwqs7HjyV8uoS7ixhHNdIdh2YiYqzClvxQKBruLwb6ESVghFjY+L1k6+d8K9",
	"4uvNNd/Y0Y+vrbw2D6+v1v8PAAD//3qVtwXvHwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
